### ISSUE TITLE
"this.getQuestionContainer is not a function" Error when setting up a 2AFC Survey 

### ISSUE THREAD

**Issue by jnyvng** [ascr-ecx/etk#4]
Hi,

I've been trying to set up a 2AFC study in Qualtrics, but it wouldn't show the sample images. When I inspected and viewed the Chrome consoles, it gives me the following error:

> vendor.b0affbef80a056e52c84.js:1 Failed to evaluate page script in page TypeError: this.getQuestionContainer is not a function
>     at eval (eval at <anonymous>

I have used the Descriptive Text Qualtrics Question Type, as well as changed the URL in the JS file to the URL where I'm hosting my images.

I am not entirely sure what I am doing wrong here? Thanks a lot in advance.

Cheers

**Comment by terryturton** [comment]
Hi jnyvng,
There is a demo on etklab.org/study-demos/2afc-example .  Look for the link at  "Take a demo survey yourself:  2AFC Demo".  Does the demo  successfully run?  

It does work for me still which makes me think that there it isn't a problem with the Qualtrics JS API.  I have changed jobs and don't have easy access to Qualtrics any more.  I do know that they have updated the JS API -- I believe you can call the methods from more than just on the page load.  But getting the question container is such a basic call that I doubt it would have changed.  

You are calling the function with the  () at the end, right?  Also, the images do need to be stored on a URL which can be openly accessed by Qualtrics.  Try setting up the question using the images on the default server and see if that works first.  If so, then it may be a server security issue on your end.  

cheers,
Terry

**Comment by jnyvng** [comment]
Hi terryturton,

Thanks for your reply. The demo runs successfully for me. And yes, I have stored the images on an accessible URL.

I am calling the function with () at the end - when I remove that, it runs and I can see my images but then I run into the next error:

> Failed to evaluate page script in page TypeError: that.hideNextButton is not a function
> at eval (eval at

When I remove the () from that function, I run into the next error:

> TypeError: Cannot read property 'appendChild' of undefined
>     at show2Images (eval at <anonymous>

So obviously just removing the () is not the way to go ;) ... 

Thanks for your help.

Cheers, Jenny

**Comment by terryturton** [comment]
Hi Jenny, 
I did not mean that you should remove the () at the end of the method.  You do need the parens.  I was asking if they were there since I was trying to think of possible errors that might cause the TypeError.  Typically a TypeError occurs due to a typo somewhere -- e.g., misspelling a function or variable name.  Since the function name is spelled correctly, there might be an error somewhere else.    I assume you are using a premium version of Qualtrics that allows use of the API?

I was able to access Qualtrics and built a one-question survey using the 2AFC github module and adding the CSS, HTML, and JS portions in the appropriate locations.  Simple cut and paste.  My only edit was to the URL to point to the sample images and it worked.  

I did notice a missing semi-colon and updated the code to reflect that just now.  However, the survey ran fine with that minor typo since many JS implementations are forgiving on missing semi-colons but perhaps that was the issue?   Do you want to try a clean implementation again from the repository code?  

Let me know how it goes.
Terry

**Comment by jnyvng** [comment]
Hi Terry,

Well, I initially had not changed anything from the code, so I was just exploring to see what might happen, hence my desperate try to remove the ().

I have tried a clean implementation by downloading the new code and the same error remains, even with the added semi-colon.

I have copy-and-pasted the CSS, HTML and JS portions according to how it was specified in ETK-2AFCREADME.docx.

And yes, I am using the premium version of Qualtrics, otherwise I wouldn't be able to add the JS code in the first place.

Never mind, I'll try something different. Thanks for your reply.

Cheers, Jenny
